services:
  web:
    build: .
    environment:
      - RAILS_MASTER_KEY
      - RAILS_ENV=development
    tty: true
    ports:
      - "3012:80"
    develop:
      watch:
        - action: sync
          path: ./app
          target: /rails/app
        - action: sync
          path: ./config
          target: /rails/config
        - action: rebuild
          path: ./Gemfile
        - action: rebuild
          path: ./Gemfile.lock
        - action: sync+restart
          path: ./config/database.yml
          target: /rails/config/database.yml
